# Generated by Django 6.0.2 on 2026-02-27 03:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "allocated_hours",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.1)]
                    ),
                ),
                ("completed_hours", models.FloatField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "generation_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completion_timestamp", models.DateTimeField(blank=True, null=True)),
                ("priority_score", models.FloatField(default=0)),
                ("integrity_flag", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocated_hours", models.FloatField()),
                ("elapsed_time", models.FloatField()),
                ("required_threshold", models.FloatField()),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studyplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planner.studyplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("deadline", models.DateField()),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(1, "Easy"), (2, "Medium"), (3, "Hard")]
                    ),
                ),
                (
                    "total_topics",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("completed_topics", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studyplan",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="planner.subject"
            ),
        ),
        migrations.CreateModel(
            name="UserInventoryTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tree_type",
                    models.CharField(
                        choices=[
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("total_earned", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_study_hours",
                    models.FloatField(
                        default=2.0,
                        validators=[django.core.validators.MinValueValidator(0.5)],
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_productive_date", models.DateField(blank=True, null=True)),
                ("selected_theme", models.CharField(default="default", max_length=50)),
                (
                    "selected_tree_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForestTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planted_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                            ("mythic", "Mythic"),
                            ("dry", "Dry"),
                            ("cut", "Cut"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tree_type", models.CharField(default="default", max_length=50)),
                ("pos_x", models.FloatField()),
                ("pos_y", models.FloatField()),
                ("depth_layer", models.IntegerField()),
                ("growth_stage", models.IntegerField(default=0)),
                ("is_protected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="planner_for_user_id_336e0a_idx"
                    ),
                    models.Index(
                        fields=["status"], name="planner_for_status_d7886c_idx"
                    ),
                    models.Index(
                        fields=["depth_layer"], name="planner_for_depth_l_decab0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["user"], name="planner_sub_user_id_07e7f5_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["deadline"], name="planner_sub_deadlin_e7f51d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "date"], name="planner_stu_user_id_1c4543_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "completed"], name="planner_stu_user_id_4a4f45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studyplan",
            index=models.Index(
                fields=["user", "date", "subject"],
                name="planner_stu_user_id_987fbb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinventorytree",
            unique_together={("user", "tree_type")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["total_points"], name="planner_use_total_p_e77ad5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["current_streak"], name="planner_use_current_e17099_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["longest_streak"], name="planner_use_longest_b410a8_idx"
            ),
        ),
    ]
