# Generated by Django 6.0.2 on 2026-02-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="save_epic",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="save_legendary",
            field=models.BooleanField(default=True),
        ),
    ]
