# Generated by Django 6.0.2 on 2026-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0002_userprofile_save_epic_userprofile_save_legendary"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_completed_tutorial",
            field=models.BooleanField(default=False),
        ),
    ]
