# Generated by Django 6.0.2 on 2026-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_userprofile_has_completed_tutorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foresttree",
            name="species",
            field=models.CharField(default="oak", max_length=50),
        ),
    ]
