# Generated by Django 6.0.2 on 2026-04-15 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0004_foresttree_species"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userinventorytree",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="userinventorytree",
            name="species",
            field=models.CharField(default="oak", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userinventorytree",
            unique_together={("user", "tree_type", "species")},
        ),
    ]
